module.exports={
    admin:{
        canModerateBlog:true,
        canAddBlogPosts:true,
        canSendFeedback:true
    },
    user:{
        canAddBlogPosts:true,
        canSendFeedback:true
    },
    banned:{
        canAddBlogPosts:false
    }
}