
export const STORE_STRING='SAMPLE_REDUCER/STORE_STRING';
export const RETURN_STRING='SAMPLE_REDUCER/RETURN_STRING';
export const SHOW_ALERT='SAMPLE_REDUCER/SHOW_ALERT';
export const HIDE_ALERT='SAMPLE_REDUCER/HIDE_ALERT';
export const CREATE_STRING='SAMPLE_REDUCER/CREATE_STRING';

export const SHOW_LOADER='APP/SHOW_LOADER';
export const HIDE_LOADER='APP/HIDE_LOADER';
export const CREATE_ASYNC_STRING='APP/CREATE_ASYNC_STRING';

export const CURRENCY_GET_CURRENCY='CURRENCY/GET_CURRENCY';
export const CURRENCY_CHANGE_BASE_CURRENCY='CURRENCY/CHANGE_BASE_CURRENCY';

