export const SHOW_LOADER='SAMPLE_REDUCER/SHOW_LOADER';
export const CREATE_STRING='SAMPLE_REDUCER/CREATE_STRING';

export const HIDE_LOADER='APP/HIDE_LOADER';
export const CREATE_ASYNC_STRING='APP/CREATE_ASYNC_STRING';

export const CURRENCY_GET_CURRENCY='CURRENCY/GET_CURRENCY';
export const CURRENCY_CHANGE_BASE_CURRENCY='CURRENCY/CHANGE_BASE_CURRENCY';

